import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import fs from 'fs';
import path from 'path';

interface ContentItem {
  id: string;
  type: string;
  title: string;
  slug: string;
}

interface HomeProps {
  contentIndex: ContentItem[];
}

export default function Home({ contentIndex }: HomeProps) {
  const pillarPages = contentIndex.filter((item) => item.type === 'pillar');
  const articlePages = contentIndex.filter((item) => item.type === 'article');
  const totalPages = contentIndex.length;
  
  return (
    <>
      <Head>
        <title>SEO-Forge Generated Site</title>
        <meta name="description" content="SEO-optimized website generated by SEO-Forge with AI-powered content" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ 
        minHeight: '100vh',
        fontFamily: 'system-ui, sans-serif',
        background: '#f8f9fa'
      }}>
        <header style={{
          background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          color: 'white',
          padding: '4rem 2rem',
          textAlign: 'center'
        }}>
          <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>🚀 SEO-Forge Site</h1>
          <p style={{ fontSize: '1.25rem', opacity: 0.9 }}>
            {totalPages} SEO-optimized pages ready
          </p>
        </header>
        
        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '2rem' }}>
          {pillarPages.length > 0 && (
            <section style={{ marginBottom: '3rem' }}>
              <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem', color: '#333' }}>
                📌 Pillar Pages
              </h2>
              <div style={{ 
                display: 'grid', 
                gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', 
                gap: '1rem' 
              }}>
                {pillarPages.map((page) => (
                  <Link key={page.id} href={`/${page.slug}`} style={{ textDecoration: 'none' }}>
                    <div style={{
                      padding: '1.5rem',
                      background: 'white',
                      borderRadius: '12px',
                      boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
                      border: '2px solid #667eea',
                      transition: 'transform 0.2s'
                    }}>
                      <span style={{ 
                        fontSize: '0.75rem', 
                        background: '#667eea', 
                        color: 'white',
                        padding: '0.25rem 0.5rem',
                        borderRadius: '4px'
                      }}>
                        PILLAR
                      </span>
                      <h3 style={{ marginTop: '0.75rem', color: '#1a1a1a' }}>{page.title}</h3>
                    </div>
                  </Link>
                ))}
              </div>
            </section>
          )}
          
          {articlePages.length > 0 && (
            <section>
              <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem', color: '#333' }}>
                📝 Articles
              </h2>
              <div style={{ 
                display: 'grid', 
                gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', 
                gap: '1rem' 
              }}>
                {articlePages.map((page) => (
                  <Link key={page.id} href={`/${page.slug}`} style={{ textDecoration: 'none' }}>
                    <div style={{
                      padding: '1.5rem',
                      background: 'white',
                      borderRadius: '12px',
                      boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
                      transition: 'transform 0.2s'
                    }}>
                      <span style={{ 
                        fontSize: '0.75rem', 
                        background: '#10b981', 
                        color: 'white',
                        padding: '0.25rem 0.5rem',
                        borderRadius: '4px'
                      }}>
                        ARTICLE
                      </span>
                      <h3 style={{ marginTop: '0.75rem', color: '#1a1a1a' }}>{page.title}</h3>
                    </div>
                  </Link>
                ))}
              </div>
            </section>
          )}
        </div>
        
        <footer style={{
          textAlign: 'center',
          padding: '2rem',
          color: '#666',
          fontSize: '0.875rem'
        }}>
          Generated by SEO-Forge
        </footer>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  // Load content index at build time for SSG compatibility
  const indexPath = path.join(process.cwd(), 'content', 'index.json');
  const indexContent = fs.readFileSync(indexPath, 'utf8');
  const contentIndex = JSON.parse(indexContent);
  
  return {
    props: {
      contentIndex
    }
  };
};
