import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>SEO-Forge Generated Site</title>
        <meta name="description" content="SEO-optimized website generated by SEO-Forge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ 
        minHeight: '100vh', 
        display: 'flex', 
        flexDirection: 'column', 
        alignItems: 'center', 
        justifyContent: 'center',
        fontFamily: 'system-ui, sans-serif',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white'
      }}>
        <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>🚀 SEO-Forge</h1>
        <p style={{ fontSize: '1.25rem', opacity: 0.9 }}>Your SEO-optimized website is ready!</p>
        <p style={{ marginTop: '2rem', opacity: 0.7 }}>Generated on 2025-12-12T03:52:44.343Z</p>
      </main>
    </>
  )
}
