import Link from 'next/link';
import { ReactNode } from 'react';

interface LayoutProps {
  children: ReactNode;
  businessName?: string;
}

const navLinks = [
  { label: 'Product', href: '/' },
  { label: 'Compare', href: '/comparisons' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'Resources', href: '/glossary' },
  { label: 'Company', href: '/about' }
];

const footerSections = [
  {
    title: 'Product',
    links: [
      { label: 'Features', href: '/' },
      { label: 'Pricing', href: '/pricing' },
      { label: 'Demo', href: '/contact' }
    ]
  },
  {
    title: 'Comparisons',
    links: [
      { label: 'See All Comparisons', href: '/comparisons' }
    ]
  },
  {
    title: 'Company',
    links: [
      { label: 'About Us', href: '/about' },
      { label: 'Case Studies', href: '/customers' },
      { label: 'Privacy Policy', href: '/privacy-policy' },
      { label: 'Terms of Service', href: '/terms-of-service' }
    ]
  },
  {
    title: 'Resources',
    links: [
      { label: 'Glossary', href: '/glossary' },
      { label: 'Blog', href: '/' }
    ]
  }
];

export default function Layout({ children, businessName = 'SEO-Forge Site' }: LayoutProps) {
  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', fontFamily: 'system-ui, -apple-system, sans-serif' }}>
      {/* Global Navigation Header */}
      <header style={{
        background: '#ffffff',
        borderBottom: '1px solid #e5e7eb',
        position: 'sticky',
        top: 0,
        zIndex: 100,
        padding: '0 2rem'
      }}>
        <div style={{
          maxWidth: '1280px',
          margin: '0 auto',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          height: '72px'
        }}>
          <Link href="/" style={{ textDecoration: 'none', fontWeight: 700, fontSize: '1.25rem', color: '#111827' }}>
            {businessName}
          </Link>
          <nav style={{ display: 'flex', gap: '2rem' }}>
            {navLinks.map(link => (
              <Link key={link.href} href={link.href} style={{
                textDecoration: 'none',
                color: '#4b5563',
                fontSize: '0.925rem',
                fontWeight: 500,
                transition: 'color 0.2s'
              }}>
                {link.label}
              </Link>
            ))}
          </nav>
          <Link href="/contact" style={{
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            color: 'white',
            padding: '0.625rem 1.25rem',
            borderRadius: '8px',
            textDecoration: 'none',
            fontWeight: 600,
            fontSize: '0.875rem'
          }}>
            Get Started
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main style={{ flex: 1 }}>
        {children}
      </main>

      {/* Fat Footer */}
      <footer style={{
        background: '#111827',
        color: '#d1d5db',
        padding: '4rem 2rem 2rem'
      }}>
        <div style={{
          maxWidth: '1280px',
          margin: '0 auto',
          display: 'grid',
          gridTemplateColumns: 'repeat(4, 1fr)',
          gap: '2rem'
        }}>
          {footerSections.map(section => (
            <div key={section.title}>
              <h4 style={{ color: '#ffffff', fontWeight: 600, marginBottom: '1rem', fontSize: '0.925rem' }}>
                {section.title}
              </h4>
              <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
                {section.links.map(link => (
                  <li key={link.href} style={{ marginBottom: '0.5rem' }}>
                    <Link href={link.href} style={{
                      color: '#9ca3af',
                      textDecoration: 'none',
                      fontSize: '0.875rem',
                      transition: 'color 0.2s'
                    }}>
                      {link.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <div style={{
          maxWidth: '1280px',
          margin: '3rem auto 0',
          paddingTop: '2rem',
          borderTop: '1px solid #374151',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          fontSize: '0.875rem',
          color: '#6b7280'
        }}>
          <p>© {new Date().getFullYear()} {businessName}. All rights reserved.</p>
          <p>Generated by SEO-Forge</p>
        </div>
      </footer>
    </div>
  );
}
